import { createClient } from '@supabase/supabase-js';

// Kredensial dari .env.local scholanext
const supabaseUrl = 'https://dwgbqhuvgrelwguphzgf.supabase.co';
const supabaseAnonKey = 'sb_publishable_JBf5EGfFPdhdSLrvCK4izA_uBm-o4UN';

const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Konfigurasi user admin baru - ganti sesuai kebutuhan
const ADMIN_EMAIL = 'admin.scholasync@gmail.com';
const ADMIN_PASSWORD = 'Admin1234!';

async function createAdminUser() {
  console.log('==================================');
  console.log('  ScholaSync - Buat User Admin');
  console.log('==================================\n');

  // Step 1: Coba signup, kalau sudah ada atau kena rate limit langsung ke login
  console.log(`📧 Mendaftarkan user: ${ADMIN_EMAIL}`);
  const { data: signUpData, error: signUpError } = await supabase.auth.signUp({
    email: ADMIN_EMAIL,
    password: ADMIN_PASSWORD,
  });

  if (signUpError) {
    if (
      signUpError.message.includes('already registered') ||
      signUpError.message.includes('security purposes')
    ) {
      console.log('⚠️  User sudah terdaftar, lanjut ke login...');
    } else {
      console.error('❌ Error saat signup:', signUpError.message);
      process.exit(1);
    }
  } else if (signUpData?.user) {
    console.log('✅ User berhasil terdaftar!');
    console.log(`   User ID: ${signUpData.user.id}`);
    if (!signUpData.user.confirmed_at) {
      console.log('\n⚠️  Email belum dikonfirmasi!');
      console.log('   Silakan konfirmasi di Supabase Dashboard:');
      console.log('   Authentication → Users → klik ✓ di sebelah email ini.\n');
      console.log('   Lalu jalankan ulang script ini.\n');
      process.exit(0);
    }
  }

  // Step 2: Login untuk mendapatkan user ID
  console.log('\n🔐 Login untuk mendapatkan session...');
  const { data: loginData, error: loginError } = await supabase.auth.signInWithPassword({
    email: ADMIN_EMAIL,
    password: ADMIN_PASSWORD,
  });

  if (loginError) {
    console.error('❌ Error saat login:', loginError.message);
    process.exit(1);
  }

  const userId = loginData.user?.id;
  console.log(`✅ Login berhasil! User ID: ${userId}`);

  // Step 3: Cek/buat tabel roles dan pastikan role 'admin' ada
  console.log('\n📋 Memeriksa tabel roles...');
  const { data: roles, error: rolesError } = await supabase
    .from('roles')
    .select('id, name')
    .eq('name', 'admin')
    .single();

  let adminRoleId;

  if (rolesError || !roles) {
    console.log('   Role admin belum ada, mencoba membuat...');
    const { data: newRole, error: createRoleError } = await supabase
      .from('roles')
      .insert({ name: 'admin' })
      .select('id')
      .single();

    if (createRoleError) {
      console.error('❌ Error membuat role admin:', createRoleError.message);
      console.log('\n⚠️  Kemungkinan tabel roles belum ada di database.');
      console.log('   Jalankan migration SQL berikut di Supabase SQL Editor:\n');
      console.log('   CREATE TABLE IF NOT EXISTS public.roles (');
      console.log('     id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,');
      console.log('     name text NOT NULL UNIQUE');
      console.log('   );');
      console.log('   INSERT INTO public.roles (name) VALUES (\'admin\') ON CONFLICT DO NOTHING;\n');
      process.exit(1);
    }
    adminRoleId = newRole.id;
    console.log(`✅ Role admin dibuat dengan ID: ${adminRoleId}`);
  } else {
    adminRoleId = roles.id;
    console.log(`✅ Role admin ditemukan dengan ID: ${adminRoleId}`);
  }

  // Step 4: Assign role admin ke user
  console.log(`\n🔗 Assign role admin ke user ${userId}...`);
  const { error: assignError } = await supabase
    .from('user_roles')
    .upsert(
      { user_id: userId, role_id: adminRoleId },
      { onConflict: 'user_id' }
    );

  if (assignError) {
    console.error('❌ Error assign role:', assignError.message);
    console.log('\n⚠️  Kemungkinan tabel user_roles belum ada. Jalankan SQL ini di Supabase:\n');
    console.log('   CREATE TABLE IF NOT EXISTS public.user_roles (');
    console.log('     id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,');
    console.log('     user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,');
    console.log('     role_id bigint NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,');
    console.log('     UNIQUE(user_id)');
    console.log('   );');
    process.exit(1);
  }

  console.log('✅ Role admin berhasil di-assign!\n');

  // Step 5: Verifikasi
  console.log('🔍 Verifikasi role user...');
  const { data: verify, error: verifyError } = await supabase
    .from('user_roles')
    .select('role:roles(name)')
    .eq('user_id', userId)
    .single();

  if (verifyError || !verify) {
    console.error('❌ Gagal verifikasi:', verifyError?.message);
  } else {
    const roleName = verify?.role?.name;
    console.log(`✅ Verifikasi sukses! User memiliki role: "${roleName}"\n`);
  }

  console.log('==================================');
  console.log('✅ ADMIN USER SIAP DIGUNAKAN!');
  console.log('==================================');
  console.log(`📧 Email    : ${ADMIN_EMAIL}`);
  console.log(`🔑 Password : ${ADMIN_PASSWORD}`);
  console.log(`🌐 URL      : http://localhost:3001/login`);
  console.log('==================================\n');
}

createAdminUser().catch(console.error);
