-- Inisialisasi Skema Database untuk Scholasync

-- 1. Membuat tabel 'schools' untuk menyimpan data profil sekolah
CREATE TABLE IF NOT EXISTS public.schools (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    address text NULL,
    logo_url text NULL,
    latitude real NULL,
    longitude real NULL,
    phone_number text NULL,
    website text NULL
);

-- Memberikan komentar pada tabel dan kolom untuk kejelasan
COMMENT ON TABLE public.schools IS 'Menyimpan informasi profil sekolah.';
COMMENT ON COLUMN public.schools.name IS 'Nama lengkap sekolah.';
COMMENT ON COLUMN public.schools.address IS 'Alamat lengkap sekolah.';
COMMENT ON COLUMN public.schools.logo_url IS 'URL ke file logo sekolah di Supabase Storage.';
COMMENT ON COLUMN public.schools.latitude IS 'Koordinat lintang lokasi sekolah.';
COMMENT ON COLUMN public.schools.longitude IS 'Koordinat bujur lokasi sekolah.';
COMMENT ON COLUMN public.schools.phone_number IS 'Nomor telepon resmi sekolah.';
COMMENT ON COLUMN public.schools.website IS 'Alamat situs web resmi sekolah.';

-- 2. Membuat tabel 'employees' untuk menyimpan data guru dan karyawan
CREATE TABLE IF NOT EXISTS public.employees (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    school_id bigint NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
    full_name text NOT NULL,
    nipy text NULL,
    birthplace text NULL,
    birthdate date NULL,
    email text NULL UNIQUE,
    whatsapp_number text NULL
);

-- Memberikan komentar pada tabel dan kolom
COMMENT ON TABLE public.employees IS 'Menyimpan data guru dan karyawan yang terhubung dengan sekolah.';
COMMENT ON COLUMN public.employees.school_id IS 'Kunci asing yang merujuk ke sekolah tempat karyawan bekerja.';
COMMENT ON COLUMN public.employees.full_name IS 'Nama lengkap karyawan.';
COMMENT ON COLUMN public.employees.nipy IS 'Nomor Induk Pegawai Yayasan (jika ada).';
COMMENT ON COLUMN public.employees.email IS 'Alamat email karyawan, harus unik.';

-- 3. Menambahkan data awal untuk sekolah
-- Aplikasi web-admin mencari sekolah dengan id=1, jadi kita buat data awalnya.
INSERT INTO public.schools (id, name, address)
VALUES (1, 'Nama Sekolah Anda', 'Alamat Sekolah Anda')
ON CONFLICT (id) DO NOTHING;
-- Mengatur ulang urutan sequence setelah penyisipan manual dengan id=1
SELECT setval(pg_get_serial_sequence('public.schools', 'id'), coalesce(max(id), 1)) FROM public.schools;


-- 4. Menyiapkan Supabase Storage untuk logo sekolah
-- Membuat bucket 'school-logos' jika belum ada.
INSERT INTO storage.buckets (id, name, public)
VALUES ('school-logos', 'school-logos', true)
ON CONFLICT (id) DO NOTHING;


-- 5. Mengatur Keamanan (Row Level Security - RLS)
-- Mengaktifkan RLS untuk tabel
ALTER TABLE public.schools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

-- Menghapus kebijakan yang mungkin ada sebelumnya
DROP POLICY IF EXISTS "Public can read school information" ON public.schools;
DROP POLICY IF EXISTS "Authenticated users can manage employees" ON public.employees;
DROP POLICY IF EXISTS "Allow public read access to logos" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to upload logos" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated users to update logos" ON storage.objects;


-- Membuat kebijakan RLS
-- Kebijakan 1: Siapa saja boleh membaca informasi sekolah.
CREATE POLICY "Public can read school information"
ON public.schools
FOR SELECT USING (true);

-- Kebijakan 2: Pengguna yang terautentikasi (login) dapat melihat, menambah, mengubah, dan menghapus data karyawan.
-- Ini adalah kebijakan awal yang bisa diperketat nanti (misal: hanya admin).
CREATE POLICY "Authenticated users can manage employees"
ON public.employees
FOR ALL USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

-- Kebijakan 3: Mengizinkan siapa saja untuk melihat file di bucket 'school-logos'.
-- Ini penting agar logo dapat ditampilkan di web.
CREATE POLICY "Allow public read access to logos"
ON storage.objects
FOR SELECT USING (bucket_id = 'school-logos');

-- Kebijakan 4: Mengizinkan pengguna yang terautentikasi untuk mengupload, mengubah logo.
CREATE POLICY "Allow authenticated users to upload logos"
ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'school-logos' AND auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to update logos"
ON storage.objects
FOR UPDATE WITH CHECK (bucket_id = 'school-logos' AND auth.role() = 'authenticated');
